### ISSUE TITLE
JScript error "No element found " on HR page

### ISSUE THREAD

**Issue by AnnaStorozhenko** [EricpolUkraine/Ajour#654]
When add some new Question set, than when  creating  new Questionnaire -  select this Question Set in dropdown, on pressing the "Save" button -  this error appears  in console.

**Comment by nazariitashak** [comment]
When method return an empty responce, ajax generate an error. It is a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=547718

**Comment by nazariitashak** [comment]
Fixed. Return value of bool type was added to SaveQuestionnaire method
